steps:
  - id: maven-build
    name: maven:3.6.0-jdk-8-alpine
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']

  - id: docker-build-migration
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ['build', '--tag=asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-migration:${_IMAGE_TAG}', 'common']

  - id: docker-build-blog-internal
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ['build', '--tag=asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-blog-internal:${_IMAGE_TAG}', 'blog-internal']

  - id: docker-build-auth
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ['build', '--tag=asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-auth:${_IMAGE_TAG}', 'auth']

  - id: docker-push-migration
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-migration:${_IMAGE_TAG}"]

  - id: docker-push-blog-internal
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-blog-internal:${_IMAGE_TAG}"]

  - id: docker-push-auth
    name: 'asia.gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/${_JOB_ID}/${_JOB_NAME}-auth:${_IMAGE_TAG}"]