steps:
  # Run maven build
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Run docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME', '.']

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yml
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME
      - --location=asia-southeast1-b
      - --cluster=your-first-cluster-1

images: ['gcr.io/$PROJECT_ID/$REPO_NAME']