steps:
  # Run maven builds.
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Run Docker build
  - name: 'docker/compose:1.19.0'
    args: ['up', '-d']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME', '.']

images: ['asia.gcr.io/$PROJECT_ID/$REPO_NAME']
