steps:
  - name: maven:3.6.0-jdk-8-alpine
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/nimbus-devops/${_JOB_NAME}-migration:${_IMAGE_TAG}', 'common']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/nimbus-devops/${_JOB_NAME}-public:${_IMAGE_TAG}', 'api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/vinid-devops/${_JOB_NAME}-public:${_IMAGE_TAG}"]