steps:
  - id: maven-build
    name: maven:3.6.0-jdk-8-alpine
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']

  - id: docker-build-migration
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/${_JOB_ID}/${_JOB_NAME}-migration:${_IMAGE_TAG}', 'common']

  - id: docker-build-api-internal
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/${_JOB_ID}/${_JOB_NAME}-api-internal:${_IMAGE_TAG}', 'api-internal']

  - id: docker-push-migration
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/${_JOB_ID}/${_JOB_NAME}-migration:${_IMAGE_TAG}"]

  - id: docker-push-api-internal
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/${_JOB_ID}/${_JOB_NAME}-api-internal:${_IMAGE_TAG}"]