steps:
  - id: maven-build
    name: maven:3.6.0-jdk-8-alpine
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']

  - id: docker-build-migration
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME-migration', 'common']

  - id: docker-build-api
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME-api', 'api']

  - id: docker-push-migration
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME-migration"]

  - id: docker-push-api
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/$PROJECT_ID/$REPO_NAME-api"]

#  - name: "gcr.io/cloud-builders/gke-deploy"
#    args:
#      - run
#      - --filename=deployment.yml
#      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:latest
#      - --location=asia-southeast1-b
#      - --cluster=your-first-cluster-1

#images: ["gcr.io/$PROJECT_ID/$REPO_NAME-api", "gcr.io/$PROJECT_ID/$REPO_NAME-migration"]