steps:
  # Run maven build
  - name: 'gcr.io/$PROJECT_ID/mvn'
    args: ['clean', 'install']

  # Run docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME', '.']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME']