apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-service
  namespace: default
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      name: nimbus-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nimbus-service
        team: nimbus
      name: nimbus-service
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: uat
          image: gcr.io/nimbus-non-prod/nimbus-service:latest
          imagePullPolicy: Always
          name: nimbus-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: docker-image-pull-secret
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nimbus-service
  namespace: default
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 75
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nimbus-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nimbus-service
  name: nimbus-service
  namespace: default
spec:
  clusterIP: 10.0.4.65
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: nimbus-service
  sessionAffinity: None
  type: ClusterIP
