version: '3.2'
services:
  liquibase:
    network_mode: host
    build: data
    environment:
      JDBC_URL: jdbc:mysql://localhost:3306/blog_service?useUnicode=true&characterEncoding=utf-8
      JDBC_USERNAME: kidabu9x
      JDBC_PASSWORD: Dota199x@
      ENVIRONMENT: prod