version: '3'
services:
  blog-internal:
    hostname: blog-internal.local
    container_name: blog-internal
    ports:
      - 48080:8080
    build: blog-internal
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker

  auth:
    hostname: auth.local
    container_name: nimbus-auth
    ports:
      - 48081:8080
    build: auth
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker

  liquibase:
    build: common
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ENVIRONMENT: local
      JDBC_MASTER_URL: jdbc:mysql://mysql/nimbus_service?useUnicode=true&characterEncoding=utf-8
      JDBC_MASTER_USERNAME: root
      JDBC_MASTER_PASSWORD:

  mysql:
    hostname: mysql.local
    container_name: nimbus-mysql
    build: docker/images/mysql
    ports:
      - 43320:3306