version: '3.2'
services:
  liquibase:
    build: common
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ENVIRONMENT: local
      JDBC_MASTER_URL: jdbc:mysql://mysql/blog_service?useUnicode=true&characterEncoding=utf-8
      JDBC_MASTER_USERNAME: root
      JDBC_MASTER_PASSWORD:

  mysql:
    command: --init-file="/tmp/init.sql"
      volumes:
        - database:/var/lib/mysql
        - ./data/init.sql:/tmp/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      ports:
        - 53320:3306

volumes:
  database:
