version: '3'
services:
  api:
    hostname: nimbus-public.local
    container_name: nimbus-api
    ports:
      - 48080:8080
    build: api-internal
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker

  mysql:
    hostname: mysql.local
    container_name: nimbus-mysql
    build: docker/images/mysql
    ports:
      - 43320:3306

  liquibase:
    build: common
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ENVIRONMENT: local
      JDBC_MASTER_URL: jdbc:mysql://mysql/nimbus_service?useUnicode=true&characterEncoding=utf-8
      JDBC_MASTER_USERNAME: root
      JDBC_MASTER_PASSWORD:
