apiVersion: apps/v1
kind: Deployment
metadata:
  name: $REPO_NAME
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      name: $REPO_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: $REPO_NAME
        team: nimbus
      name: $REPO_NAME
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT
          image: gcr.io/$GCP_PROJECT_ID/$REPO_NAME:$COMMIT_SHA
          imagePullPolicy: Always
          name: $REPO_NAME
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
              name: nimbus-internal
      imagePullSecrets:
        - name: docker-image-pull-secret
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: $REPO_NAME
spec:
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 75
      type: Resource
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: $REPO_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: $REPO_NAME
  name: $REPO_NAME
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: $REPO_NAME
  type: ClusterIP
