apiVersion: apps/v1
kind: Deployment
metadata:
  name: $JOB_NAME
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable # during the rolling update
  selector:
    matchLabels:
      name: $JOB_NAME
  template:
    metadata:
      name: $JOB_NAME
      labels:
        name: $JOB_NAME
        team: vinpay
    spec:
      containers:
        - name: $JOB_NAME
          image: asia.gcr.io/nimbus-devops/$JOB_NAME:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: ELASTIC_APM_METRICS_INTERVAL
              value: 0s
          envFrom:
            - secretRef:
                name: $CI_PROJECT_NAME
            - configMapRef:
                name: nimbus-public
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: $JOB_NAME
  name: $JOB_NAME
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: $JOB_NAME
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $JOB_NAME
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: $JOB_NAME
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
