version: '3.2'
services:
  blog-internal:
    hostname: blog-internal.$ENVIRONMENT
    container_name: blog-internal
    ports:
      - ${PORT}0:8080
    build: blog-internal
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: docker

  blog-public:
    hostname: blog-public.$ENVIRONMENT
    container_name: blog-public
    ports:
      - ${PORT}1:8080
    build: blog-public
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: $ENVIRONMENT

  auth:
    hostname: auth.local
    container_name: nimbus-auth
    ports:
      - ${PORT}2:8080
    build: auth
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      ENVIRONMENT: $ENVIRONMENT

  liquibase:
    build: common
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ENVIRONMENT: $ENVIRONMENT
      JDBC_MASTER_URL: jdbc:mysql://mysql/nimbus_service?useUnicode=true&characterEncoding=utf-8
      JDBC_MASTER_USERNAME: root
      JDBC_MASTER_PASSWORD:

  mysql:
    hostname: mysql.$ENVIRONMENT
    container_name: nimbus-mysql
    build: docker/images/mysql
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    ports:
      - ${PORT}20:3306

volumes:
  ${DB_VOLUME}:
