apiVersion: v1
kind: ConfigMap
metadata:
  name: billservice-common
data:
  VERSION: $IMAGE_TAG
  JDBC_MASTER_URL: jdbc:mysql://vep-mysql-master.int.vinid.dev:3306/billservice_dev
  JDBC_MASTER_USERNAME: billservice_dev
  JDBC_SLAVE_URL: jdbc:mysql://vep-mysql-replicas.int.vinid.dev:3306/billservice_dev
  JDBC_SLAVE_USERNAME: billservice_dev
  REDIS_HOST: redis-master
  REDIS_PORT: "6379"
  ENVIRONMENT: dev
