name: Build and deploy

on:
  push:
    branches:
      - master
      - uat
  pull_request:
    branches:
      - master
      - uat

env:
  GKE_CLUSTER: main
  GKE_ZONE: asia-southeast1-b
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  JOB_ORIGINAL_NAME: nimbus
  GATEWAY: nimbus-gateway

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build
        run: |-
          mvn $MAVEN_OPTS clean package

  deploy:
    runs-on: ubuntu-latest
    needs: [maven_build]
    steps:
      - uses: actions/checkout@v2
        # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.NONPROD_GKE_SA_EMAIL }}
          service_account_key: ${{ secrets.NONPROD_GKE_SA_KEY }}
          project_id: ${{ secrets.NONPROD_GKE_PROJECT }}

        # Configure Docker to use the gcloud command-line tool as a credential
        # helper for authentication
      - name: authorize gcloud
        run: |-
          gcloud --quiet auth configure-docker

      - name: authorize gke
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_ZONE" --project "${{ secrets.NONPROD_GKE_PROJECT }}"
          echo "K8S CLUSTER: `kubectl config current-context`"

      - name: run cloudbuild
        run: |-
          gcloud builds submit \
          --config=cloudbuild.yml \
          --substitutions=_JOB_NAME=$JOB_ORIGINAL_NAME,_IMAGE_TAG=$GITHUB_SHA,_JOB_ID=${{ secrets.NONPROD_GKE_PROJECT }} \

      - name: deploy auth to uat
        env:
          ENVIRONMENT: uat
          HOST: auth-uat.nimbus.com.vn
          SERVICE_PATH: /
          GCP_PROJECT_ID: ${{ secrets.NONPROD_GKE_PROJECT }}
          JOB_NAME: nimbus-auth
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          cd auth/deploy/k8s/uat && bash deploy-uat.sh

      - name: deploy blog internal to uat
        env:
          ENVIRONMENT: uat
          HOST: api-internal-uat.nimbus.com.vn
          SERVICE_PATH: /
          GCP_PROJECT_ID: ${{ secrets.NONPROD_GKE_PROJECT }}
          JOB_NAME: nimbus-blog-internal
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          cd blog-internal/deploy/k8s/uat && bash deploy-uat.sh

      - name: deploy migration to uat
        env:
          ENVIRONMENT: uat
          GCP_PROJECT_ID: ${{ secrets.NONPROD_GKE_PROJECT }}
          JOB_NAME: nimbus-migration
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          cd common/deploy/k8s/uat && bash deploy-uat.sh

#      - name: expose
#        run: |-
#          kubectl apply -f ingress.yml -n uat
